CREATE TABLE [dbo].[BOLETA] (
    [ID]            NUMERIC (10) IDENTITY (1, 1) NOT NULL,
    [MAPA]          NUMERIC (10) NOT NULL,
    [FUNCION]       NUMERIC (10) NOT NULL,
    [SALA]          NUMERIC (10) NOT NULL,
    [LOCALIDAD]     NUMERIC (10) NOT NULL,
    [NUM_SIL]       NUMERIC (10) NOT NULL,
    [COD_VEN]       NUMERIC (10) NOT NULL,
    [SEC_CLIENTE]   NUMERIC (10) NOT NULL,
    [VALOR_BOL_VEN] NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_BOLETA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BOLETA_CLIENTE] FOREIGN KEY ([SEC_CLIENTE]) REFERENCES [dbo].[CLIENTE] ([SEC_CLI]),
    CONSTRAINT [FK_BOLETA_FUNCION] FOREIGN KEY ([FUNCION]) REFERENCES [dbo].[FUNCION] ([ID]),
    CONSTRAINT [FK_BOLETA_LOCALIDAD] FOREIGN KEY ([LOCALIDAD]) REFERENCES [dbo].[LOCALIDAD] ([ID]),
    CONSTRAINT [FK_BOLETA_MAPA] FOREIGN KEY ([MAPA]) REFERENCES [dbo].[MAPA] ([ID]),
    CONSTRAINT [FK_BOLETA_SALA] FOREIGN KEY ([SALA]) REFERENCES [dbo].[SALA] ([ID]),
    CONSTRAINT [FK_BOLETA_SILLA] FOREIGN KEY ([NUM_SIL]) REFERENCES [dbo].[SILLA] ([NUM_SIL]),
    CONSTRAINT [FK_BOLETA_TTU_BOLETA] FOREIGN KEY ([ID]) REFERENCES [dbo].[BOLETA] ([ID]),
    CONSTRAINT [FK_BOLETA_VENTA] FOREIGN KEY ([COD_VEN]) REFERENCES [dbo].[VENTA] ([ID])
);

