CREATE TABLE [dbo].[CLIENTE] (
    [SEC_CLI]   NUMERIC (10)   IDENTITY (1, 1) NOT NULL,
    [DOCUMENTO] NUMERIC (15)   NOT NULL,
    [NOMBRE]    NVARCHAR (50)  NOT NULL,
    [APELLIDO1] NVARCHAR (20)  NULL,
    [APELLIDO2] NVARCHAR (20)  NULL,
    [TELEFONO]  NVARCHAR (25)  NULL,
    [DIRECCION] NVARCHAR (200) NULL,
    [EMAIL]     NVARCHAR (200) NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED ([SEC_CLI] ASC)
);

