CREATE TABLE [dbo].[FUNCION] (
    [ID]        NUMERIC (10) IDENTITY (1, 1) NOT NULL,
    [FECHA_FUN] DATETIME     NOT NULL,
    [PELICULA]  NUMERIC (10) NOT NULL,
    [RESERVAS]  CHAR (1)     NULL,
    CONSTRAINT [PK_FUNCION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FUNCION_FUNCION] FOREIGN KEY ([ID]) REFERENCES [dbo].[FUNCION] ([ID]),
    CONSTRAINT [FK_FUNCION_PELICULA] FOREIGN KEY ([PELICULA]) REFERENCES [dbo].[PELICULA] ([ID])
);

