CREATE TABLE [dbo].[LOCALIDAD] (
    [ID]            NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [SALA]          NUMERIC (10)    NOT NULL,
    [NOMBRE]        NVARCHAR (200)  NOT NULL,
    [OBSERVACIONES] NVARCHAR (4000) NULL,
    CONSTRAINT [PK_LOCALIDAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LOCALIDAD_SALA] FOREIGN KEY ([SALA]) REFERENCES [dbo].[SALA] ([ID])
);

