CREATE TABLE [dbo].[LOCALIDAD_MAPA] (
    [ID]        NUMERIC (10) IDENTITY (1, 1) NOT NULL,
    [LOCALIDAD] NUMERIC (10) NOT NULL,
    [MAPA]      NUMERIC (10) NOT NULL,
    [COSTO]     NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_LOCALIDAD_MAPA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LOCALIDAD_MAPA_LOCALIDAD] FOREIGN KEY ([LOCALIDAD]) REFERENCES [dbo].[LOCALIDAD] ([ID]),
    CONSTRAINT [FK_LOCALIDAD_MAPA_MAPA] FOREIGN KEY ([MAPA]) REFERENCES [dbo].[MAPA] ([ID])
);

