CREATE TABLE [dbo].[RESERVA] (
    [ID]              NUMERIC (5)  IDENTITY (1, 1) NOT NULL,
    [FUNCION]         NUMERIC (10) NOT NULL,
    [NUM_SIL]         NUMERIC (10) NOT NULL,
    [FECHA_RES]       DATETIME     NOT NULL,
    [TIPO_RES]        CHAR (1)     NOT NULL,
    [SEC_CLIENTE]     NUMERIC (10) NOT NULL,
    [ESTADO]          CHAR (1)     NOT NULL,
    [SILLA_LOCALIDAD] NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_RESERVA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_RESERVA_CLIENTE] FOREIGN KEY ([SEC_CLIENTE]) REFERENCES [dbo].[CLIENTE] ([SEC_CLI]),
    CONSTRAINT [FK_RESERVA_FUNCION] FOREIGN KEY ([FUNCION]) REFERENCES [dbo].[FUNCION] ([ID]),
    CONSTRAINT [FK_RESERVA_SILLA_MAPA] FOREIGN KEY ([SILLA_LOCALIDAD]) REFERENCES [dbo].[SILLA_LOCALIDAD_MAPA] ([ID])
);

