CREATE TABLE [dbo].[SALA] (
    [ID]            NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [NOMBRE]        NVARCHAR (200)  NOT NULL,
    [OBSERVACIONES] NVARCHAR (4000) NULL,
    [DIRECCION]     NVARCHAR (150)  NULL,
    [RUTA_IMG]      NVARCHAR (200)  NULL,
    CONSTRAINT [PK_SALA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

