CREATE TABLE [dbo].[SILLA] (
    [NUM_SIL]   NUMERIC (10)    IDENTITY (1, 1) NOT NULL,
    [LOCALIDAD] NUMERIC (10)    NOT NULL,
    [NOM_FIL]   NVARCHAR (200)  NOT NULL,
    [FIL_SIL]   NUMERIC (5)     NOT NULL,
    [COL_SIL]   NUMERIC (5)     NOT NULL,
    [OBS_SIL]   NVARCHAR (4000) NULL,
    CONSTRAINT [PK_SILLA] PRIMARY KEY CLUSTERED ([NUM_SIL] ASC),
    CONSTRAINT [FK_SILLA_LOCALIDAD] FOREIGN KEY ([LOCALIDAD]) REFERENCES [dbo].[LOCALIDAD] ([ID])
);

