CREATE TABLE [dbo].[SILLA_LOCALIDAD_MAPA] (
    [ID]        NUMERIC (10) IDENTITY (1, 1) NOT NULL,
    [LOCALIDAD] NUMERIC (10) NOT NULL,
    [NUM_SIL]   NUMERIC (10) NOT NULL,
    [MAPA]      NUMERIC (10) NOT NULL,
    [ESTADO]    NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_SILLA_LOCALIDAD_MAPA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SILLA_LOCALIDAD_MAPA_LOCALIDAD] FOREIGN KEY ([LOCALIDAD]) REFERENCES [dbo].[LOCALIDAD] ([ID]),
    CONSTRAINT [FK_SILLA_LOCALIDAD_MAPA_MAPA] FOREIGN KEY ([MAPA]) REFERENCES [dbo].[MAPA] ([ID])
);

