CREATE TABLE [dbo].[VENTA] (
    [ID]          NUMERIC (10) IDENTITY (1, 1) NOT NULL,
    [SEC_CLIENTE] NUMERIC (10) NOT NULL,
    [FECHA_VEN]   DATE         NOT NULL,
    [SUBTOTAL]    NUMERIC (10) NOT NULL,
    [TOTAL]       NUMERIC (10) NOT NULL,
    [FUNCION]     NUMERIC (10) NOT NULL,
    [RESP_VEN]    NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_VENTA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_VENTA_CLIENTE] FOREIGN KEY ([SEC_CLIENTE]) REFERENCES [dbo].[CLIENTE] ([SEC_CLI]),
    CONSTRAINT [FK_VENTA_FUNCION] FOREIGN KEY ([FUNCION]) REFERENCES [dbo].[FUNCION] ([ID])
);

